
;ODD OR EVEN: 	IF VALUE IN ACCUMULATOR IS ODD, C IS 0H, 
;		IF VALUE IN ACCUMULATOR IS EVEN, C IS FFH.

jmp start

;data


;code
start: nop

MVI A, 3H;SET ACCUMULATOR VALUE
RRC; MOVES BITS TO THE RIGHT (IF LAST BIT IS 1[ODD] CARRY FLAG IS SET)
JC ODD; JUMP TO ODD IF CARRY FLAG IS SET

MVI C, 0FFH; SET C TO FFH IF NOT ODD(EVEN)
JMP DONE ;SKIP ODD

ODD: MVI C, 00H ; SET C TO 00H IF ACCUMULATOR IS ODD

DONE: NOP

hlt